name: Jaksim31-Frontend CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "develop" ]
    
jobs:
  Jaksim31-Front:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      
      - name: Create env file
        run: echo "${{ secrets.ENV_FILE }}" > .env
          
      # NPM install & Build
      - name: Install and Build
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
      - run: npm install sharp
      - run: npm run build
      
      # NPM caching
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          
      # Docker Buildx Setting
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Docker Login
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          # Username used to log against the Docker registry
          username: ${{ secrets.DOCKER_ID }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker Build & Push    
      - name: Docker Build and push
        uses: docker/build-push-action@v2
        with:
            context: .
            file: ./Dockerfile
            platforms: linux/amd64
            push: true
            tags: r2god7k/jaksim31-frontend:latest
            cache-from: type=gha    # gha=Github Action Cache
            cache-to: type=gha,mode=max

      # SSH Connect - (Web1)
      - name: Deploy to Web1
        uses: appleboy/ssh-action@master
        with: 
            host: ${{ secrets.REMOTE_IP }}
            username: ${{ secrets.REMOTE_SSH_ID }}
            key: ${{ secrets.REMOTE_SSH_KEY }}
            port: ${{ secrets.REMOTE_SSH_PORT }}
            script: |
              ls -a
              sudo su
              # sudo chmod 666 /var/run/docker.sock
              sudo /usr/sbin/groupadd -f docker
              sudo /usr/sbin/usermod -aG docker `user`
              sudo chown root:docker /var/run/docker.sock
              docker pull r2god7k/jaksim31-frontend:latest
              docker stop jaksim31-frontend
              docker rm jaksim31-frontend
              docker run -d -p 3000:3000 --name jaksim31-front --network centos_default r2god7k/jaksim31-frontend:latest
          
          
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          # Check the following URLs one by one sequentially
          url: https://jaksim31.xyz
          # Follow redirects, or just report success on 3xx status codes
          follow-redirect: false # Optional, defaults to "false"
          # Fail this action after this many failed attempts
          max-attempts: 10 # Optional, defaults to 1
          # Delay between retries
          retry-delay: 5s # Optional, only applicable to max-attempts > 1
          # Retry all errors, including 404. This option might trigger curl upgrade.
          retry-all: false # Optional, defaults to "false"

            
      # SSH Connect - (Web2)
      - name: Deploy to Web2
        uses: appleboy/ssh-action@master
        with: 
            host: ${{ secrets.REMOTE_IP }}
            username: ${{ secrets.REMOTE_SSH_ID }}
            key: ${{ secrets.REMOTE_SSH_KEY }}
            port: ${{ secrets.REMOTE_SSH_PORT_2 }}
            script: |
              ls -a
              sudo su
              # sudo chmod 666 /var/run/docker.sock
              sudo /usr/sbin/groupadd -f docker
              sudo /usr/sbin/usermod -aG docker `user`
              sudo chown root:docker /var/run/docker.sock
              docker pull r2god7k/jaksim31-frontend:latest
              docker stop jaksim31-frontend
              docker rm jaksim31-frontend
              docker run -d -p 3000:3000 --name jaksim31-front --network centos_default r2god7k/jaksim31-frontend:latest

